sudo: required
services:
  - docker

before_install:
  - docker build -t taewookimdev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true taewookimdev/react-test npm run test

after_success:
  - docker build -t taewookimdev/multi-client ./client
  - docker build -t taewookimdev/multi-nginx ./nginx
  - docker build -t taewookimdev/multi-server ./server
  - docker build -t taewookimdev/multi-worker ./worker
  # Log in to the Docker CLI
  # Add Environment variables in Travis-CLI - DOCKER_ID, DOCKER_PASSWORD
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images to Docker hub
  - docker push taewookimdev/multi-client
  - docker push taewookimdev/multi-nginx
  - docker push taewookimdev/multi-server
  - docker push taewookimdev/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-745674676916
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"  